config/routes.rb
Rails.application.routes.draw do
  
  root 'index#index'

  get '/setup/step_1', :to=> 'setup#step_1'
  post '/setup/step_2', :to=> 'setup#step_2'
  post '/setup/step_3', :to=> 'setup#step_3'
  post '/setup/step_4', :to=> 'setup#step_4'
  
  get '/blog/:id/:name', :to=> 'posts#show'
  
  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
  match '/auth/destroy', :to => 'sessions#destroy', via: [:delete]
  
  get '/about', :to => 'about#index'
  get "/admin", :to => 'admin#index'
  resources :categories
  resources :posts

end

app/views/admin/index.html.erb
<div id="vb_admin_posts">
  <h2>
    posts
  </h2>
  <div>
    <small>posts per page</small>
    <%=[10, 20, 50, 100].collect do |n|
      link_to n, "/admin?posts_per_page=#{n}"
    end.join.html_safe%>
  <table>
    <tbody>
      <thead>
        <tr>
        <% %w[title published views category last_modified].each do |h|%>
          <th>
            <%=link_to h, "/admin?sort_posts_by="+url_encode(h), :title=>"sort posts by #{h}"%>
          </th>
        <%end%> 
    	</tr>
      </thead>
      <%@posts.each do |post|%>
        <tr>
          <td>
            <%=link_to post.title, post%>
          </td>
          <td>
            <%=if post.published then "yes" else "no" end%>
          </td>
          <td>
            <%=post.views%>
          </td>
          <td>
            <%=post.category.name%>
          </td>
          <td>
            <%=post.updated_at.to_date%>
          </td>
        </tr>  
      <%end%>  
    </tbody>    
  </table> 
</div>

<div id="vb_admin_categories">
  <h2>
    categories
  </h2>
  <table>
    <tbody>
  	  <%@categories.each do |cat|%>
  	  <tr>
  	  	<td>
  	  	  <%=link_to cat.name, cat%>
  	  	</td>
  	  	<td>
  	  	  <%=link_to "edit", edit_category_path(cat)%>
  	  	</td>
  	  	<% if @categories.length > 1%>
  	  	<td>
  	  	  <%= link_to 'remove', cat, method: :delete%>
	  	</td>
	  	<%end%>
	   </tr> 	
	 <%end%>
  	</tbody>
  </table>
</div>