config/routes.rb
Rails.application.routes.draw do
  
  root 'index#index'

  get '/setup/step_1', :to=> 'setup#step_1'
  post '/setup/step_2', :to=> 'setup#step_2'
  post '/setup/step_3', :to=> 'setup#step_3'
  post '/setup/step_4', :to=> 'setup#step_4'
  
  get '/blog/:id/:name', :to=> 'posts#show'
  
  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
  match '/auth/destroy', :to => 'sessions#destroy', via: [:delete]
  
  get '/about', :to => 'about#index'
  get "/admin", :to => 'admin#index'
  resources :categories
  resources :posts

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Dashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="loadCurtain" style="position:fixed; top:0; left:0; width:100%; height:100%; background:white; margin:0;">
</div>
<header id="vb_admin_header">
  <h1>
  	<a href="/admin">
  	  Admin Dashboard
    </a>
  </h1>
  <nav>
  <%=link_to "view live site", "/"%>
  <%=link_to "new post", new_post_path%>
  <%=link_to "new category", new_category_path%>
  <%=link_to "edit about page", "about/edit"%>
  <%=link_to "settings", "admin/settings"%>
  </nav>
</header>
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>
<%= yield %>
<footer id="vb_admin_footer">
  <script type="text/javascript">
    $(document).on('page:change', function () 
    {
      $('#loadCurtain').fadeOut();
    });
  </script>
</footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=Rails.application.class.parent.to_s%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript">
    applyTheme = function(){ return true; } 
  </script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<div id="loadCurtain" style="position:fixed; top:0; left:0; width:100%; height:100%; background:white; margin:0;">
  <noscript>
    Sorry, but JavaScript must be enable to view this page.
  </noscript>
</div>
<header id="vb_header">
  <h1>
  	<a href="/">
  	  <%=@blog.title%>
  	</a>
  </h1>
  <nav>
    <a href="/about">
      about
    </a>
    <a href="/posts">
      posts
    </a>
    <a href="/categories">
      categories
    </a>
    <%=if is_admin? then link_to "admin","/admin" end%> 
  </nav>
</header>
<%= yield %>
<footer id="vb_footer">
  <script type="text/javascript">
    $(document).on('page:change', function () 
    {
      applyTheme();
      $('#loadCurtain').fadeOut();
    });
  </script>
</footer>
</body>
</html>